apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: demo-connect-cluster
spec:
  bootstrapServers: 'demo-cluster-kafka-bootstrap:9093'
  config:
    config.storage.replication.factor: -1
    config.storage.topic: connect-cluster-configs
    group.id: connect-cluster
    offset.storage.replication.factor: -1
    offset.storage.topic: connect-cluster-offsets
    status.storage.replication.factor: -1
    status.storage.topic: connect-cluster-status
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-connect-metrics
        key: metrics-config.yml
  replicas: 1
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: demo-cluster-cluster-ca-cert
  version: 3.2.3
