apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    name: mysql