kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: orders
  labels:
    app: orders
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'orders:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-11-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/davgordo/camel-mysql'
    contextDir: /
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial