kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/cykumar/camel-springboot-mysql.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: orders
  labels:
    app: orders
    app.kubernetes.io/component: orders
    app.kubernetes.io/instance: orders
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: camel-mysql
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-ubi8